version: "3.9"
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            POSTGRESS_DB: petprojectapi
            POSTGRESS_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
           - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
    